"""add more indexes for tasks

Revision ID: 0012
Revises: 0011
Create Date: 2026-06-01 10:06:34.404789

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_schedules_deadline",
        "schedules",
        ["scheduler_id", "deadline_at"],
        unique=False,
        postgresql_where=sa.text("enabled IS true"),
    )
    op.create_index("ix_tasks_hash_created", "tasks", ["hash", sa.literal_column("created_at DESC")], unique=False)
    op.create_index(
        "ix_tasks_org_scheduler_modified_status",
        "tasks",
        ["organisation", "scheduler_id", sa.literal_column("modified_at DESC"), "status"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_org_type_created",
        "tasks",
        ["organisation", "type", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_tasks_queue_polling",
        "tasks",
        ["scheduler_id", "status", "priority", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'QUEUED'"),
    )
    op.create_index("ix_tasks_schedule_status", "tasks", ["schedule_id", "status"], unique=False)
    op.create_index(
        "ix_tasks_scheduler_modified_status",
        "tasks",
        ["scheduler_id", sa.literal_column("modified_at DESC"), "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_scheduler_modified_status", table_name="tasks")
    op.drop_index("ix_tasks_schedule_status", table_name="tasks")
    op.drop_index("ix_tasks_queue_polling", table_name="tasks", postgresql_where=sa.text("status = 'QUEUED'"))
    op.drop_index("ix_tasks_org_type_created", table_name="tasks")
    op.drop_index("ix_tasks_org_scheduler_modified_status", table_name="tasks")
    op.drop_index("ix_tasks_hash_created", table_name="tasks")
    op.drop_index("ix_schedules_deadline", table_name="schedules", postgresql_where=sa.text("enabled IS true"))
    # ### end Alembic commands ###
