"""add various indexes, and change others to reflect usage

Revision ID: 0013
Revises: 0012
Create Date: 2026-06-29 12:56:20.261670

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_type"), table_name="tasks")
    op.create_index("ix_tasks_type", "tasks", ["type", sa.literal_column("created_at DESC")], unique=False)
    op.create_index(
        "ix_tasks_sched_org_input_ooi_created",
        "tasks",
        [
            "organisation",
            "scheduler_id",
            sa.literal_column("(data ->> 'input_ooi')"),
            sa.literal_column("created_at DESC"),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_sched_org_input_ooi_created", table_name="tasks")
    op.drop_index("ix_tasks_type", table_name="tasks")
    op.create_index(op.f("ix_tasks_type"), "tasks", ["type"], unique=False)
    # ### end Alembic commands ###
