"""add index for boefje_meta org+boefje_id+inputooi in desc order

Revision ID: 2380422e773e
Revises: 1dde0213e9fe
Create Date: 2026-06-29 12:44:37.532792

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2380422e773e"
down_revision = "1dde0213e9fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_boefje_meta_lookup",
        "boefje_meta",
        ["organization", "boefje_id", "input_ooi", sa.literal_column("started_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_boefje_meta_lookup", table_name="boefje_meta")
    # ### end Alembic commands ###
